name: Migration

on:
  push:
    branches:
      # - 'main'
      - 'feature/migracao'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  migracao_job:
    name: Migracao Job
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
 
      - name: Login Azure
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}" \
            --allow-no-subscriptions
      
      - name: Get AAD token for Databricks
        id: aad
        run: |
          TOKEN=$(az account get-access-token \
            --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d \
            --query accessToken -o tsv)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Migration
        env: 
          DATABRICKS_TOKEN: ${{ steps.aad.outputs.token }}
        run: |
          $jobs = databricks jobs list --output json | ConvertFrom-Json \

          $filtered = $jobs | Where-Object { $_.settings.name -match '(?i)\[${{ secrets.DATA_TEAM }}\]' }\

          foreach ($job in $filtered) { 
              $job_id   = $job.job_id 
              $job_name = $job.settings.name 

              databricks bundle generate job --existing-job-id $job_id --bind  --config-dir "resources/jobs/migrados" --source-dir "resources/notebooks/migrados" --force 

              Write-Host "OK  -> $job_id | $job_name" 
          }

